server:
  port: 9000

spring:
  application:
    name: rabbit-ucenter-server
  #DataSource配置(MySQL)
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #数据库连接
    url: jdbc:mysql://localhost:3306/zlsoft_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123