#_配置文件内容加密
jasypt:
  encryptor:
    password: rabbit

#_tomcat配置
server:
  tomcat:
    max-threads: 200 #_tomcat起动的最大线程数，即同时处理的任务个数，默认值为200
    min-spare-threads: 50 #_最小备用线程数，tomcat启动时的初始化的线程数

#_http上传下载文件参数设置
spring:
  http:
    multipart:
      max-file-size: 1000MB #_上传文件的最大长度
      max-request-size: 1000MB #_请求文件的最大值
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379

#_redis过期时间设置
redis:
  cache:
    expiration: 3600